// Try catch using the error
try {
	console.log('Try')
}
catch (err) {
	console.log('Error:', err)
}

// Try catch without using the error
try {
	console.log('Try')
}
catch (err) {
	console.log('Error')	
}